version: '3'

services:
  client:
    container_name: dashboard
    build:
      args:
        NODE_ENV: production
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
